cloud:
  aws:
    credentials:
      accessKey: AKIAU6GDX422LNDHEG5C
      secretKey: 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
    s3:
      bucketName: ndolphin
    region:
      static: ap-northeast-2
    stack:
      auto: false
