spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    include: private
  devtools:
    livereload:
      enabled:false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ndolphin?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        show_sql: true

  # 이메일 전송 SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: ndolphin207@gmail.com
    password: fobp vxrr yaiv veqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # OAUTH2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e6ff767d2e5031bca0b656aafb9febe9
            client-secret: 2WEEEzewAZflGwr14CqvfAoy6dGP7mn9
            redirect-uri: "http://localhost:8080/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
          naver:
            client-id: Y9J0WjXpfsZSP_7cnM5B
            client-secret: gRJPO9Y0u1
            redirect-uri: "http://localhost:8080/oauth2/callback/naver"
            authorization-grant-type: authorization_code
            scope: email
          google:
            client-id: 702397908111-l29ht012g25isqhvou2ev4i7r9im9aa9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# JWT 설정 추가
jwt:
  secret-key: "ThisStatementIsJwtSecretKeyDoNotUseThisStatement"
#  header: Authorization
#  token-validity-in-seconds: 86400

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql: trace
