app:
  baseUrl: "http://i11d207.p.ssafy.io"
#  baseUrl: "http://ec2-54-180-146-64.ap-northeast-2.compute.amazonaws.com"
#  baseUrl: "http://localhost:8080"
spring:
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: private
  devtools:
    livereload:
      enabled:false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.146.64:3306/ndolphin?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/ndolphin?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_SECRET}
    hikari:
      pool-name: hikari-pool
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#        use_sql_comments: true
#        show_sql: true
        # 생성, 업데이트 시간 자동 설정
        jdbc:
          time_zone: Asia/Seoul

  # OAUTH2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: "${app.baseUrl}:8080/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: account_email
          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: "${app.baseUrl}:8080/oauth2/callback/naver"
            authorization-grant-type: authorization_code
            scope: email
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "${app.baseUrl}:8080/oauth2/callback/google"
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# JWT 설정 추가
jwt:
  secret-key: "ThisStatementIsJwtSecretKeyDoNotUseThisStatement"
#  header: Authorization
#  token-validity-in-seconds: 86400

logging:
#  level:
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: debug

#    org.hibernate.type.descriptor.sql: trace
openai:
  api-key: ${OPENAI_SECRET}
  model: gpt-3.5-turbo
  api-url: https://api.openai.com/v1/chat/completions
  timeout: 3000  # Optional timeout setting for API requests

